# Generated by Django 2.1.4 on 2019-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='token',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
