# Generated by Django 2.1.4 on 2019-04-16 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loggedinuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedinuser',
            name='login_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 16, 11, 16, 24, 913162, tzinfo=utc)),
        ),
    ]
